# Generated by Django 6.0.7 on 2026-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='coffee_house',
        ),
        migrations.DeleteModel(
            name='CoffeeHouse',
        ),
    ]
